apiVersion: v1
kind: Service
metadata:
  name:  ttrend-rtp-service
  namespace: ttrend
spec:
  type: NodePort
  selector:
    app: ttrend-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000